return {
  custom_highlights = function(colors)
    return {
      NormalFloat = { bg = colors.surface0 },
      FloatBorder = { fg = colors.overlay0 },
      VertSplit = { bg = colors.base, fg = colors.surface1 },
      FoldColumn = { fg = colors.overlay0, bg = colors.mantle },
      LineNr = { fg = colors.overlay0, bg = colors.mantle },
      CursorLineNr = { fg = colors.mauve, bg = colors.surface0, style = {} },
      CursorLineSign = { bg = colors.surface0 },
      CursorLineFold = { bg = colors.surface0 },
      -- SignColumn = { bg = colors.mantle },
      Pmenu = { bg = colors.mantle, fg = "" },
      PmenuSel = { bg = colors.surface0, fg = colors.subtext0 },
      LazySpecial = { style = {} },
      LazyProgressDone = { fg = colors.blue, style = { "nocombine" } },
      LazyProgressTodo = { fg = colors.overlay0, style = { "nocombine" } },

      IndentBlanklineContextChar = { fg = colors.peach },
      TelescopePreviewNormal = { bg = colors.crust },
      TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },

      IndentBlanklineChar = { fg = colors.blue },
      -- IndentBlanklineContextChar = { fg = colors.surface2 },
      GitSignsChange = { fg = colors.peach },
      GitSignsCurrentLineBlame = { fg = colors.crust, bg = colors.surface2 },
      -- Blamer = { fg = colors.overlay1, bg = colors.base },
      -- NvimTreeIndentMarker = { link = "IndentBlanklineChar" },
      -- NvimTreeExecFile = { fg = colors.text },
      String = { fg = colors.yellow },
      Function = { fg = colors.green },
      ["@function.macro"] = { fg = colors.mauve },
      Type = { fg = colors.blue },
      ["@type.builtin.cpp"] = { fg = colors.blue, style = { "bold" } },
      ["@type.builtin"] = { fg = colors.blue, style = { "bold" } },
      ["@lsp.type.type"] = {},
      Structure = { fg = colors.teal },
      Comment = { fg = colors.overlay1 },
      cTypedef = { fg = colors.pink, style = { "italic" } },
      cDefine = { fg = colors.pink, style = { "italic" } },
      cStructure = { fg = colors.yellow },
      StorageClass = { fg = colors.pink, style = { "italic" } },
      cStorageclass = { fg = colors.pink, style = { "italic" } },
      PreProc = { fg = colors.flamingo, style = { "italic", "nocombine" } },
      Keyword = { fg = colors.maroon },
      Conditional = { fg = colors.red },
      Repeat = { fg = colors.red },
      ["@keyword.return"] = { fg = colors.flamingo, style = { "bold", "italic", "nocombine" } },
      ["@parameter"] = { fg = colors.sapphire, style = { "italic" } },
      ["@property"] = { fg = colors.subtext1 },
      WinBar = { fg = colors.overlay2, bg = colors.mantle },
      -- TabLineSel = { bg = colors.pink },
      -- CmpBorder = { fg = colors.surface2 },
      --  Pmenu = { bg = C.none },
      MatchParen = { fg = colors.lavender, bg = colors.surface0, style = {} },
      ["@lsp.type.property.c"] = {},
      ["@function.call.c"] = { fg = colors.green, style = { "bold", "italic", "nocombine" } },
      ["@lsp.type.property.lua"] = {},
      ["@variable.member"] = { fg = colors.subtext1 },
    }
  end,
  styles = {
    comments = { "italic", "nocombine" },
    conditionals = { "italic" },
    loops = { "italic", "nocombine" },
    functions = { "bold", "italic" },
    keywords = { "italic", "nocombine" },
    strings = {},
    variables = { "nocombine" },
    numbers = {},
    booleans = { "italic" },
    properties = {},
    types = {},
    operators = {},
  },

  highlight_overrides = {
    --   all = function(colors)
    --     return {
    --       -- Comment = { fg = colors.flamingo },
    --     }
    --   end,
  },
}
