return {
    alpha = true,
    sandwich = false,
    noice = true,
    mini = true,
    leap = true,
    markdown = true,
    neotest = true,
    cmp = true,
    overseer = true,
    lsp_trouble = true,
    -- ts_rainbow2 = true,
    rainbow_delimiters = true,
    mason = true,
    neotree = true,
    notify = true,
    which_key = true,
    treesitter = true,
    -- treesitter_context = true,
    aerial = true,
    semantic_tokens = true,
    -- symbols_outline = true,
    telescope = { enabled = true, style = "nvchad" },
    dap = { enabled = true, enable_ui = true },
    gitsigns = true,
    indent_blankline = {
        enabled = true,
        colored_indent_levels = false,
    },
    native_lsp = {
        enabled = true,
        virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = {},
            information = {},
        },
        underlines = {
            errors = {},
            hints = {},
            warnings = {},
            information = {},
        },
        inlay_hints = {
            background = true,
        },
    },
}
